### ISSUE TITLE
Collecting Image Data & Preprocessing - 2

### ISSUE THREAD

**Issue by Joonkkyo** [kookmin-sw/2019-cap1-2019_6.io#12]
1. 학습시킬 이미지 데이터 (라바콘, 검지 손가락) 새로 수집 (각각 200장)
2. 학습시킬 이미지 데이터에 대한 labeling 및 경로 설정

**Comment by byunghoonpark** [comment]
[Collecting Image Data & Preprocessing]

본 프로젝트에서는 시각장애인이 장애물로 인식할 볼라드(여기선 안전뿔로 대채)와 글자를 가리킬 손가락 이미지를 모아서 학습한다.  따라서 볼라드 200장, 손가락 200장을 수집 후 이미지 데이터에 대해 Yolomark를 이용해 라벨링을 한다. 이 때, 손가락과 볼라드의 클래스 넘버는 각각 0, 1이다. 라벨링 후 /darknet/Yolomark/x64/Release/data의 img 폴더에 이미지 파일과 좌표가 적힌 .txt파일들이 생성된다. 프로그램 실행을 위해 현 경로에 존재하는 img 폴더는 /darknet 으로, obj.data obj.names train.txt는 /darknet/data/ 경로로 이동시켜 준다. 또한 train.txt에 적힌 파일들의 경로도 현 위치로 수정한다.

**Comment by byunghoonpark** [comment]
[Collecting Image Data & Preprocessing]

추가적인 데이터 학습 실시. 정면에서 바라본 이미지 뿐만 아니라 다양한 각도에서 이미지 수집 후 학습 재개.
