### ISSUE TITLE
Transformed .xml test on Raspberry Pi3 b+

### ISSUE THREAD

**Issue by eunyyyoung** [kookmin-sw/2019-cap1-2019_6.io#15]
#6 

`python3 openvino_tiny-yolov3_MultiStick_test.py -numncs 1`

 .xml .bin 파일로 변환해서 라즈베리 파이에서 돌아가는지 test

frozen_darknet_yolov3_model.xml
frozen_darknet_yolov3_model.bin 
생성됨

**Comment by eunyyyoung** [comment]
같은 오류: https://github.com/PINTO0309/OpenVINO-YoloV3/issues/7
오류 해결안됨, detection 안됨

**Comment by eunyyyoung** [comment]
openvino_tiny-yolov3_MultiStick_test.py에 
num = 3 (o)
6은 IndexError

**Comment by sangminns** [comment]
.mapping 도 같이 옮기니 해결됨

> 같은 오류: [PINTO0309/OpenVINO-YoloV3#7](https://github.com/PINTO0309/OpenVINO-YoloV3/issues/7)
> 오류 해결안됨, detection 안됨
