### ISSUE TITLE
라바콘, 검지 손가락 학습된 가중치파일(weights)로 YOLO 실행 - 1

### ISSUE THREAD

**Issue by eunyyyoung** [kookmin-sw/2019-cap1-2019_6.io#17]
#8 

- [x] 병훈 (우분투 16.04)

- [ ] 은영 (mac OS Mojave)

**Comment by byunghoonpark** [comment]
학습을 위한 cfg 파일은 yolov3-tiny.cfg 파일을 이용. 오차율이 가장 적은 weight 파일로 오브젝트 디텍션 수행. 라바콘 인식 성공

**Comment by byunghoonpark** [comment]
검지손가락 또한 인식 성공 ( 단, 하얀 배경을 전제 )
