### ISSUE TITLE
yolov3-tiny버전으로 학습한 weights파일로 모델 최적화 & test on Raspberry Pi3 b+

### ISSUE THREAD

**Issue by eunyyyoung** [kookmin-sw/2019-cap1-2019_6.io#20]
#18

**Comment by eunyyyoung** [comment]
yolo_v3_tiny.json 파일 num : 3 으로 변경

라파이에서 detection이 안되고
sendPingMessage 오류남

**Comment by sangminns** [comment]
OpenVINO version 2018 R5 에서 2019 R1으로 버전 업데이트 후 해결 완료
