### ISSUE TITLE
Finger Detection using openCV

### ISSUE THREAD

**Issue by eunyyyoung** [kookmin-sw/2019-cap1-2019_6.io#21]
- [ ] 병훈: 영상에서 손가락인식 후 이미지로 저장 구현

- [x] 은영: 이미지에서 손끝으로부터 바운더리 구현

**Comment by byunghoonpark** [comment]
OpenCV를 이용한 손가락 인식 구현 
1. 손 동작 인식, 스킨 컬러를 이용한 손 검출
2. 거리 변환 행렬을 이용하여 손의 중심점 찾기
3. 찾은 중심점으로부터 손가락의 개수를 세서 지정한 손가락의 개수와 같다면 이미지 저장 

- 문제점  :  사람의 피부와 유사한 물체를 손가락으로 인식

**Comment by byunghoonpark** [comment]
위의 방식으로 코드를 구현하고 실행해본 결과 주변의 상황에 따라 잡음이 많이 반영되어 제대로 된 검출이 불가했다. 대안책으로 손가락에 대한 기계학습을 선행하고, 영상에 들어온 이미지들에 대한 관심영역을 설정한 뒤 기존에 학습했던 손가락과의 비교를 통해 검출해야 할 것 같다.

**Comment by byunghoonpark** [comment]
[ 참고 ]
image hog feature svm classfication
https://github.com/tatsuyah/vehicle-detection

**Comment by eunyyyoung** [comment]
바운더리를 구현하기 위해 일단은 영상으로부터 피부색으로 손을 검출하는 코드로 구현.
손 끝의 좌표를 구해 손 끝 좌표의 윗 부분의 이미지만 자른 뒤, ITT API에서 text를 잘 가져올 수 있도록 이미지를 1024x768 크기에 맞춰 나머지 부분은 검은색 이미지로 합쳐 저장한다.
