### ISSUE TITLE
Collecting Image Data & Preprocessing - 3 & Data Learning - 3

### ISSUE THREAD

**Issue by Joonkkyo** [kookmin-sw/2019-cap1-2019_6.io#25]
1. 최종 데모 때 사용할 장애물 및 오브젝트 선정 후 데이터 수집 ( 스마트폰 카메라로 촬영 )
2. 학습시킬 이미지 데이터에 대한 labeling 및 경로 설정
3. yolo tiny v3 모델을 이용하여 학습 진행
4. 클래스 당 300장, 10만 번씩 학습 진행

**Comment by Joonkkyo** [comment]
class 4일때 filter 크기 27로 설정, 데이터를 모으고 한번에 학습을 시켜야 오류가 발생하지 않는듯

**Comment by byunghoonpark** [comment]
학습 및 yolov3-tiny 사용 관련링크 
https://eungbean.github.io/2018/11/07/yolo-for-realtime-food-recognition/ 
https://pgmrlsh.tistory.com/6?category=766787

**Comment by byunghoonpark** [comment]
1. 오르막 계단 150장, 내리막 계단 150장에 대한 전처리 과정을 거쳤다. 
2. 볼라드와 손가락이 15만번 학습된 weight 파일에 기존의 이미지들을 삭제하고 2만번의 학습을 추가했다. 17만번의 학습이 진행된 weight 파일로 오브젝트 디텍션을 실행했을 때, 볼라드 및 계단 어느것도 인식하지 못하였다.

**Comment by Joonkkyo** [comment]
labeling number
0 finger
1 bollard
2 upstair
3 downstair
4 extinguisher

**Comment by Joonkkyo** [comment]
finger - 200장, bollard - 300장, upstair - 250장, downstair - 250장, extinguisher - 200장

**Comment by Joonkkyo** [comment]
filter를 33으로 설정하고 모든 데이터에 대해 학습 진행 중

**Comment by 20143068** [comment]
90000번 (손실 함수값 : 0.06)으로 테스트해본 결과 볼라드, 손가락은 잘 인식하나 소화기, 계단은 전혀 인식하지 못하는 것으로 확인. 배경을 다양하게 하여 다시 데이터를 수집하고 학습을 진행할 예정.

**Comment by byunghoonpark** [comment]
학습 후 장애물들에 대한 인식 실패. 실패원인은 cfg파일에서 filter 수정이 제대로 되지 않았고 batch 사이즈도 64가 아닌 24 로 되어 있었다. 또한 train.txt에 학습시킨 데이터들의 경로가 명시되어 있지 않았고 obj.names. obj.date 파일들에 대한 수정도 올바르게 되어 있지 않았다. 

학습에 관련한 파일들을 수정하고 다시 학습 재개
