### ISSUE TITLE
우분투에서 학습시킨 weights파일로 YOLO 실행 - 3

### ISSUE THREAD

**Issue by eunyyyoung** [kookmin-sw/2019-cap1-2019_6.io#28]
#25

**Comment by byunghoonpark** [comment]
<filter>
classes = 4
filter = 33

<obj.names>
extinguisher
stair
bollard
finger

**Comment by byunghoonpark** [comment]
4000번의 학습으로 소화기 인식 성공

**Comment by byunghoonpark** [comment]
학습 후 장애물들에 대한 인식 실패. 실패원인은 cfg파일에서 filter 수정이 제대로 되지 않았고 batch 사이즈도 64가 아닌 24 로 되어 있었다. 또한 train.txt에 학습시킨 데이터들의 경로가 명시되어 있지 않았고 obj.names. obj.date 파일들에 대한 수정도 올바르게 되어 있지 않았다.

학습에 관련한 파일들을 수정하고 다시 학습 재개
