### ISSUE TITLE
Raspberry Pi3 b+ 전력문제 해결 및 FPS 향상  

### ISSUE THREAD

**Issue by eunyyyoung** [kookmin-sw/2019-cap1-2019_6.io#29]
라즈베리파이3 b+ 기본 권장 전력은 5V 2.5A 로 
시연시 전력 공급을 위해 일반적으로 쓰는 보조배터리(5V 2A)를 이용하면 전력 부족 표시가 뜬다.

**Comment by byunghoonpark** [comment]
라즈베리파이의 전력문제 해결을 위해 5v 3a 보조베터리 이용, 전력 문제 해결되지 않음

**Comment by byunghoonpark** [comment]
1024 x 768 의 윈도우 사이즈를 320 x 240 으로 줄여 카메라 FPS, 객체 인식 FPS를 높였고 
라즈베리파이의 전력문제를 해소했다.
