### ISSUE TITLE
Raspberry 원격 설정하기

### ISSUE THREAD

**Issue by eunyyyoung** [kookmin-sw/2019-cap1-2019_6.io#30]

**Comment by sangminns** [comment]
라즈베리파이에서 모니터, 마우스, 키보드를 연결하지 않고 사용할 수 있도록 한다. 따라서 라즈베리파이에는 최종적으로 카메라, NCS2 USB, 전원 공급 장치만 연결한다. 

라즈베리파이와 원격으로 제어할 PC를 같은 공유기(무선랜)를 연결하여 IP주소를 확인하고 윈도우 환경에서 원격 데스크톱을 실행하여 사용한다.

**Comment by byunghoonpark** [comment]
원격 실행시 export DISPLAY=:0.0
