### ISSUE TITLE
Collecting Image Data & Preprocessing - 5 & Data Learning - 5

### ISSUE THREAD

**Issue by Joonkkyo** [kookmin-sw/2019-cap1-2019_6.io#34]
1. 계단에 대한 인식률을 별도로 테스트하기 위해 1488장의 image data를 수집
2. 학습시킬 이미지 데이터에 대한 labeling 및 경로 설정
3. yolo tiny v3 모델을 통해 1만 번 학습 후 이미지에 대한 인식률 측정

**Comment by byunghoonpark** [comment]
2시간 동안 약 5000번의 학습. 학습 이후 소화기와 계단 인식이 성공하면 모든 장애물 요소들을 추가하여 최종학습을 실행할 예정

**Comment by byunghoonpark** [comment]
1만번 학습 후 생긴 weight 파일로 오브젝트 디텍션 수행 결과, 소화기와 계단 모두 인식 성공
본 프로젝트에서 계획한 모든 데이터들을 최종으로 학습시킬 예정
