### ISSUE TITLE
Collecting Image Data & Preprocessing - 7 & Data Learning - 7

### ISSUE THREAD

**Issue by byunghoonpark** [kookmin-sw/2019-cap1-2019_6.io#42]
소화기 600장 추가, 볼라드 100장 추가하여 학습

**Comment by Joonkkyo** [comment]
2만 번 학습 => 손실함수 값 : 0.25
볼라드, 계단은 잘 인식하나, 소화기에 대해서 약간 저조한 인식률을 보였음
6만 번 학습 => 손실함수 값 : 0.14
이전보다 소화기에 대해서 약간 개선된 인식률을 보임

**Comment by byunghoonpark** [comment]
10만 번 학습 => 손실함수 값 : 0.108
