### ISSUE TITLE
학습 모델 최적화(Model Optimizer)(20000번 학습한 weights 파일) & Raspberry Pi3 b+에서 테스트 - 1

### ISSUE THREAD

**Issue by sangminns** [kookmin-sw/2019-cap1-2019_6.io#44]
볼라드, 소화기, 계단을 20000번 학습한 모델 파일을 Model Optimizer 과정을 통해 xml, bin 파일로 변환한다. 이 변환 과정을 거쳐서 나오는 .xml, .bin, .mapping 파일은 라즈베리파이에서 NCS2를 통해 Yolo 알고리즘을 사용하는데 필요하다.

**Comment by eunyyyoung** [comment]
#42
