### ISSUE TITLE
Install the Intel® Distribution of OpenVINO™ toolkit for Linux

### ISSUE THREAD

**Issue by eunyyyoung** [kookmin-sw/2019-cap1-2019_6.io#5]
참고: https://software.intel.com/en-us/articles/OpenVINO-Install-Linux

**Comment by sangminns** [comment]
리눅스에서 설치한 OpenViNO 버전은 2018 R5 이다. 직접 학습한 모델은 OpenVINO 툴킷에서 제공하는 Model Optimizer 작업을 거쳐야한다. 여기서 최적화된 모델을 실시간 객체 인식 알고리즘 yolo에 적용시켜 실행할 수 있다.
