### ISSUE TITLE
Model Optimizer

### ISSUE THREAD

**Issue by eunyyyoung** [kookmin-sw/2019-cap1-2019_6.io#6]
기존 yolov3-tiny.weights 이용

참고: 
- https://software.intel.com/en-us/articles/OpenVINO-ModelOptimizer
- https://software.intel.com/en-us/articles/OpenVINO-Using-TensorFlow

**Comment by eunyyyoung** [comment]
`python3 convert_weights_pb.py --class_names coco.names --data_format NHWC --weights_file yolov3-tiny.weights --tiny`

.pb 파일 생성

`python mo_tf.py --input_model ~{경로}/frozen_darknet_yolov3_model.pb 
--tensorflow_use_custom_operations_config {경로}/yolo_v3_tiny.json 
--data_type=FP16 
--input_shape=[1,416,416,3] or --batch 1`

.xml .bin 파일 생성

**Comment by sangminns** [comment]
Yolo Darknet 프레임워크에서 학습한 모델은 OpenVINO에서 제공하는 yolo 환경에서 실행되지 않는다. 따라서 OpenVINO에서 제공하는 Model Optimizer라는 모델 최적화 작업이 필요하다. 이 작업을 거쳐서 변환된 모델은 라즈베리파이에서 NCS2와 연동하여 yolo 실행이 가능하다.
