### ISSUE TITLE
Collecting Image Data & Preprocessing - 1

### ISSUE THREAD

**Issue by eunyyyoung** [kookmin-sw/2019-cap1-2019_6.io#7]
라바콘, 검지 손가락 사진

1. Yolo_mark 사용
`git clone https://github.com/AlexeyAB/Yolo_mark`

2. YOLO_MARK Labeling
bounding box의 좌표값 txt파일로 저장

**Comment by byunghoonpark** [comment]
txt파일에 적히는 값들은 사진은 중앙값 + 가로길이, 세로길이

**Comment by Joonkkyo** [comment]
GPU 연산에 필요한 CUDA 라이브러리를 설치하였음, 학습 시 발생하던 오류 모두 수정됨

**Comment by Joonkkyo** [comment]
해당 학습은 yolo v2 모델을 통해 진행하였음, 학습 데이터 : 각 클래스 당 300장, 학습 횟수 : 45000회, 학습 시간 : 25시간
