### ISSUE TITLE
Data Learning - 1

### ISSUE THREAD

**Issue by eunyyyoung** [kookmin-sw/2019-cap1-2019_6.io#8]
#7 

1. convolutional layer 설치
http://pjreddie.com/media/files/darknet19_448.conv.23

2. 데이터 학습 - yolov3 버전

**Comment by Joonkkyo** [comment]
GTX 1080을 이용하여 30시간동안 총 80000번의 학습을 진행하였고, 최종적인 손실 함수의 값은 0.04이다.

**Comment by byunghoonpark** [comment]
현재 15만번 이상의 학습 실시. 10만번째에서 생긴 weight 파일이 인식률이 가장 좋음. 15만번을 기점으로 overfitting이 발생.
